name: ootoc

on:
  push:
    branches: master

jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git submodule update --init --recursive
      - name: Envirment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get install -y build-essential cmake libcurl4-openssl-dev
      - uses: mxschmitt/action-tmate@v1
      - name: yaml
        run: |
          git clone https://github.com/jbeder/yaml-cpp.git
          cd yaml-cpp
          cmake -DYAML_CPP_BUILD_TESTS:BOOL=OFF -DYAML_BUILD_SHARED_LIBS:BOOL=ON .
          make
          sudo make install
      - name: spdlog
        run: |
          git clone https://github.com/gabime/spdlog.git
          cd spdlog
          cmake -DSPDLOG_BUILD_TESTS:BOOL=OFF -DSPDLOG_BUILD_SHARED:BOOL=ON -DSPDLOG_BUILD_EXAMPLE:BOOL=OFF .
          make
          sudo make install
      - name: libtar
        run: |
          git clone https://github.com/ElonH/libtar.git
          cd libtar
          autoreconf --force --install
          ./configure
          make
          sudo make install
      - name: Make
        run: |
          cmake -DOOTOC_BUILDIN_LIBTAR:BOOL=OFF .
          make
          make test
