name: ootoc

on:
  push:
    branches: master

jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git submodule update --init --recursive
      - name: Envirment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get install -y build-essential cmake libcurl4-openssl-dev
      - name: yaml
        run: |
          git clone https://github.com/jbeder/yaml-cpp.git
          cd yaml-cpp
          cmake .
          make
          sudo make install
      - name: Make
        run: |
          cmake .
          make
